@startuml

enum Type {
    Boid(maxSpeed = 32.0, radius=0.1)
    SpecialEntity(maxSpeed = 64.0, radius=1.0)
}

class Entity {
    - id: Int
    - type: Type
    - radius: Double
    - position: Vector3D
    - velocity: Vector3D
    + toXYZ(): String
    + sees(other: Entity): Bool
    + distance(other: Entity): Double
}

Type *-left- Entity: uses

@enduml
